- src/main/java/gladiator/philosopher/account/controller/AccountController.java
- src/main/java/gladiator/philosopher/account/dto/AccountRequestDto.java
- src/main/java/gladiator/philosopher/account/dto/SignInResponseDto.java
- src/main/java/gladiator/philosopher/account/entity/Account.java
- src/main/java/gladiator/philosopher/account/service/AccountService.java
- src/main/java/gladiator/philosopher/account/service/AccountServiceImpl.java
> fix : account 네이밍 규칙 및 관련 이슈 수정 (#13)

- src/main/java/gladiator/philosopher/notification/controller/NotificationController.java
- src/main/java/gladiator/philosopher/notification/dto/NotificationDto.java
- src/main/java/gladiator/philosopher/notification/entity/Notification.java
- src/main/java/gladiator/philosopher/notification/repository/NotificationRepository.java
- src/main/java/gladiator/philosopher/notification/service/NotificationService.java
- src/main/java/gladiator/philosopher/notification/service/NotificationServiceImpl.java
- src/main/java/gladiator/philosopher/post/entity/Post.java
- src/main/java/gladiator/philosopher/post/entity/PostImages.java
- src/main/java/gladiator/philosopher/report/controller/ReportController.java
- src/main/java/gladiator/philosopher/report/dto/ReportDto.java
- src/main/java/gladiator/philosopher/report/entity/Report.java
- src/main/java/gladiator/philosopher/report/entity/ReportCategory.java
- src/main/java/gladiator/philosopher/report/repository/ReportRepository.java
- src/main/java/gladiator/philosopher/report/service/ReportService.java
- src/main/java/gladiator/philosopher/report/service/ReportServiceImpl.java
- src/main/java/gladiator/philosopher/thread/controller/ThreadController.java
- src/main/java/gladiator/philosopher/thread/dto/ThreadDto.java
- src/main/java/gladiator/philosopher/thread/entity/Thread.java
- src/main/java/gladiator/philosopher/thread/entity/ThreadStatus.java
- src/main/java/gladiator/philosopher/thread/repository/ThreadRepository.java
- src/main/java/gladiator/philosopher/thread/service/ThreadService.java
- src/main/java/gladiator/philosopher/thread/service/ThreadServiceImpl.java
report, notification, thread 기본 아키텍쳐 생성
> 기본 베이스 엔티티 생성 작업(#21)

- .gitignore
- src/main/java/gladiator/philosopher/account/controller/ProfileController.java
- src/main/java/gladiator/philosopher/account/dto/EditProfileRequestDto.java
- src/main/java/gladiator/philosopher/account/dto/SignUpRequestDto.java
- src/main/java/gladiator/philosopher/account/entity/Account.java
- src/main/java/gladiator/philosopher/account/service/AccountServiceImpl.java
- src/main/java/gladiator/philosopher/account/service/ProfileService.java
- src/main/java/gladiator/philosopher/account/service/ProfileServiceImpl.java
- src/main/java/gladiator/philosopher/security/SecurityConfig.java
accountImage 정상 동작 완료 및 리팩터링(#18)
> accountImage 정상 동작 완료 및 리팩터링(#18)

- src/main/java/gladiator/philosopher/account/repository/AccountRepository.java
- src/main/java/gladiator/philosopher/admin/controller/AdminController.java
- src/main/java/gladiator/philosopher/admin/dto/UserInfoResponseDto.java
- src/main/java/gladiator/philosopher/admin/service/AdminService.java
- src/main/java/gladiator/philosopher/admin/service/AdminServiceImpl.java
"과연 어드민은 어떤 기능을 필요로 할까"에서 출발한 설계로 100% 다 구현하지는 않았음, 빠른 시일 내에 작업 완료 할 것
> feat : 어드민 API 설계 및 추가적인 기능 API 기능 구현 (#8) 

- src/main/java/gladiator/philosopher/thread/controller/ThreadController.java
- src/main/java/gladiator/philosopher/thread/dto/ThreadDto.java
- src/main/java/gladiator/philosopher/thread/dto/ThreadResponseDto.java
- src/main/java/gladiator/philosopher/thread/dto/ThreadSimpleResponseDto.java
- src/main/java/gladiator/philosopher/thread/entity/Thread.java
- src/main/java/gladiator/philosopher/thread/repository/ThreadRepository.java
- src/main/java/gladiator/philosopher/thread/service/ThreadService.java
- src/main/java/gladiator/philosopher/thread/service/ThreadServiceImpl.java
> Thread 객체 및 관련 로직 구체 구현(#34)

- src/main/java/gladiator/philosopher/comment/entity/Comment.java
- src/main/java/gladiator/philosopher/comment/service/CommentService.java
- src/main/java/gladiator/philosopher/comment/service/CommentServiceImpl.java
- src/main/java/gladiator/philosopher/post/entity/Post.java
- src/main/java/gladiator/philosopher/post/service/PostService.java
- src/main/java/gladiator/philosopher/post/service/PostServiceImpl.java
- src/main/java/gladiator/philosopher/report/controller/ReportController.java
- src/main/java/gladiator/philosopher/report/dto/ReportRequestDto.java
- src/main/java/gladiator/philosopher/report/entity/Report.java
- src/main/java/gladiator/philosopher/report/repository/ReportRepository.java
- src/main/java/gladiator/philosopher/report/service/ReportService.java
- src/main/java/gladiator/philosopher/report/service/ReportServiceImpl.java
- src/main/java/gladiator/philosopher/thread/entity/Thread.java
- src/main/java/gladiator/philosopher/thread/service/ThreadService.java
- src/main/java/gladiator/philosopher/thread/service/ThreadServiceImpl.java
> 게시글, 댓글, 쓰레드 신고 API 구현(#36)

- src/main/java/gladiator/philosopher/recommend/controller/RecommendController.java
- src/main/java/gladiator/philosopher/recommend/entity/Recommend.java
- src/main/java/gladiator/philosopher/recommend/repository/RecommendRepository.java
- src/main/java/gladiator/philosopher/recommend/service/RecommendService.java
- src/main/java/gladiator/philosopher/recommend/service/RecommendServiceImpl.java
> feat: Recommend 관련 세부 로직 추가(#44)

- src/main/java/gladiator/philosopher/comment/controller/CommentController.java
- src/main/java/gladiator/philosopher/comment/entity/Comment.java
- src/main/java/gladiator/philosopher/comment/repository/CommentRepository.java
- src/main/java/gladiator/philosopher/comment/service/CommentService.java
- src/main/java/gladiator/philosopher/comment/service/CommentServiceImpl.java
> feat: Comment 관련 로직 수정(#46)

- src/main/java/gladiator/philosopher/common/exception/ExceptionStatus.java
- src/main/java/gladiator/philosopher/post/entity/Post.java
- src/main/java/gladiator/philosopher/post/service/PostService.java
Post 수정 삭제 ExceptionStatus 상태코드 추가하였습니다
> feat: Post 수정 삭제 ExceptionStatus 상태코드 추가(#10)

- src/main/java/gladiator/philosopher/post/service/PostService.java
- src/main/java/gladiator/philosopher/post/service/PostServiceImpl.java
- src/main/java/gladiator/philosopher/recommend/controller/RecommendController.java
- src/main/java/gladiator/philosopher/recommend/repository/RecommendRepository.java
- src/main/java/gladiator/philosopher/recommend/service/RecommendService.java
- src/main/java/gladiator/philosopher/recommend/service/RecommendServiceImpl.java
- src/main/java/gladiator/philosopher/thread/service/ThreadServiceImpl.java
Recommend Controller, Service, Repository 수정
postService -> existsPostId 메소드 생성 및 주석 처리
> refator: Recommend Controller, Service, Repository 수정(#61)

- src/main/java/gladiator/philosopher/common/config/RedisConfig.java
- src/main/java/gladiator/philosopher/common/util/EmailMessage.java
- src/main/java/gladiator/philosopher/common/util/RedisUtil.java
- src/main/java/gladiator/philosopher/common/util/VerifyController.java
- src/main/java/gladiator/philosopher/common/util/VerifyEmailService.java
Email 인증 로직 구현 및 redis 적용(#64)
> Email 인증 로직 구현 및 redis 적용(#64)

- src/main/java/gladiator/philosopher/account/controller/AccountController.java
- src/main/java/gladiator/philosopher/account/dto/SignInResponseDto.java
- src/main/java/gladiator/philosopher/account/service/AccountService.java
- src/main/java/gladiator/philosopher/account/service/AccountServiceImpl.java
- src/main/java/gladiator/philosopher/common/config/RedisConfig.java
- src/main/java/gladiator/philosopher/common/config/SecurityConfig.java
- src/main/java/gladiator/philosopher/common/jwt/JwtAuthenticationFilter.java
- src/main/java/gladiator/philosopher/common/jwt/JwtTokenProvider.java
- src/main/java/gladiator/philosopher/common/jwt/TokenDto.java
- src/main/java/gladiator/philosopher/common/jwt/TokenRequestDto.java
- src/main/java/gladiator/philosopher/common/util/RedisUtil.java
JWT 리프레시 토큰 구현 및 Redis 적용, 로그아웃 구현(#25)
> JWT 리프레시 토큰 구현 및 Redis 적용, 로그아웃 구현(#25)

- src/main/java/gladiator/philosopher/post/dto/PostResponseDto.java
- src/main/java/gladiator/philosopher/post/entity/Post.java
- src/main/java/gladiator/philosopher/post/service/PostService.java
- src/main/java/gladiator/philosopher/post/service/PostServiceImpl.java
- src/main/java/gladiator/philosopher/thread/entity/Thread.java
PostResponseDto에 추천개수 나타내는 로직을 추가하였습니다.
> feat: PostResponseDto에 추천개수 나타내는 로직 추가(#37)

- src/main/java/gladiator/philosopher/comment/controller/CommentController.java
- src/main/java/gladiator/philosopher/comment/repository/CommentRepository.java
- src/main/java/gladiator/philosopher/comment/service/CommentService.java
- src/main/java/gladiator/philosopher/comment/service/CommentServiceImpl.java
Comment 수정/삭제시 작성자를 확인하는 로직을 추가하였습니다.
> feat: Comment 수정/삭제시 작성자 확인 로직 추가(#62)

- src/main/java/gladiator/philosopher/notification/service/NotificationService.java
- src/main/java/gladiator/philosopher/notification/service/NotificationServiceImpl.java
- src/main/java/gladiator/philosopher/post/controller/PostController.java
- src/main/java/gladiator/philosopher/post/entity/PostOpinion.java
- src/main/java/gladiator/philosopher/post/service/PostService.java
- src/main/java/gladiator/philosopher/post/service/PostServiceImpl.java
- src/main/java/gladiator/philosopher/recommend/service/RecommendServiceImpl.java
- src/main/java/gladiator/philosopher/thread/entity/Thread.java
- src/main/java/gladiator/philosopher/thread/service/ThreadServiceImpl.java
좋아요 2 이상이면 쓰레드 생성하는 로직을 구현하였습니다.
> feat: 좋아요 2 이상이면 쓰레드 생성하는 로직 구현(#37)

- src/main/java/gladiator/philosopher/recommend/entity/Recommend.java
Recommend entity에 cascade = CascadeType.ALL 추가하였습니다.
> refactor: Recommend entity에 cascade = CascadeType.ALL 추가(#10)

- src/main/java/gladiator/philosopher/common/filter/CorsFilter.java
프론트 서버와 Cors issue 해결을 위한 CorsFilter 추가 및 기능 확인 완료
> feat: CorsFilter 추가(#98)

- src/main/java/gladiator/philosopher/PhilosopherApplication.java
- src/main/java/gladiator/philosopher/thread/controller/ThreadController.java
- src/main/java/gladiator/philosopher/thread/entity/Thread.java
- src/main/java/gladiator/philosopher/thread/repository/ThreadRepository.java
- src/main/java/gladiator/philosopher/thread/service/ThreadService.java
- src/main/java/gladiator/philosopher/thread/service/ThreadServiceImpl.java
Thread 관련 스케줄러 기능을 추가하였습니다 - 시간 수정 필요합니다
> feat: 스케줄러 기능 추가 - thread(#123)

- src/main/java/gladiator/philosopher/admin/dto/ThreadsSimpleResponseDtoByAdmin.java
- src/main/java/gladiator/philosopher/comment/service/CommentServiceImpl.java
- src/main/java/gladiator/philosopher/thread/controller/ThreadController.java
- src/main/java/gladiator/philosopher/thread/dto/ThreadResponseDto.java
- src/main/java/gladiator/philosopher/thread/dto/ThreadSimpleResponseDto.java
- src/main/java/gladiator/philosopher/thread/entity/Thread.java
- src/main/java/gladiator/philosopher/thread/repository/ThreadCustomRepositoryImpl.java
- src/main/java/gladiator/philosopher/thread/repository/ThreadOpinionRepository.java
- src/main/java/gladiator/philosopher/thread/repository/ThreadRepository.java
- src/main/java/gladiator/philosopher/thread/service/ThreadService.java
- src/main/java/gladiator/philosopher/thread/service/ThreadServiceImpl.java
refactor: Thread 불필요 양방향연관관계 삭제(#135)
> refactor: Thread 불필요 양방향연관관계 삭제(#135)

- src/main/java/gladiator/philosopher/common/util/InitData.java
- src/main/java/gladiator/philosopher/post/repository/PostImageRepository.java
- src/main/java/gladiator/philosopher/post/repository/PostOpinionRepository.java
- src/main/java/gladiator/philosopher/post/service/PostService.java
- src/main/java/gladiator/philosopher/post/service/PostServiceImpl.java
- src/main/java/gladiator/philosopher/thread/service/ThreadServiceImpl.java
> init data 수정 및 post 의존성 제거

- src/main/java/gladiator/philosopher/account/controller/AccountController.java
- src/main/java/gladiator/philosopher/account/dto/AccountCommentDto.java
- src/main/java/gladiator/philosopher/account/service/AccountService.java
- src/main/java/gladiator/philosopher/comment/dto/CommentResponseDto.java
- src/main/java/gladiator/philosopher/comment/repository/CommentRepository.java
- src/main/java/gladiator/philosopher/comment/service/CommentService.java
- src/main/java/gladiator/philosopher/comment/service/CommentServiceImpl.java
Account 본인이 작성한 Comment 페이징 조회 구현하였습니다.
> feat: Account 본인이 작성한 Comment 페이징 조회(#146)

- src/main/java/gladiator/philosopher/category/service/CategoryServiceImpl.java
- src/main/java/gladiator/philosopher/recommend/entity/CommentRecommend.java
- src/main/java/gladiator/philosopher/recommend/entity/PostRecommend.java
- src/main/java/gladiator/philosopher/recommend/entity/ThreadRecommend.java
- src/test/java/gladiator/philosopher/category/CategoryControllerTest.java
- src/test/java/gladiator/philosopher/category/CategoryServiceTest.java
- src/test/java/gladiator/philosopher/category/CategoryTest.java
- src/test/java/gladiator/philosopher/comment/CommentControllerTest.java
- src/test/java/gladiator/philosopher/comment/CommentServiceTest.java
- src/test/java/gladiator/philosopher/comment/CommentTest.java
- src/test/java/gladiator/philosopher/factory/AccountFactory.java
- src/test/java/gladiator/philosopher/factory/CategoryFactory.java
- src/test/java/gladiator/philosopher/factory/CommentFactory.java
- src/test/java/gladiator/philosopher/factory/NotificationFactory.java
- src/test/java/gladiator/philosopher/factory/PostFactory.java
- src/test/java/gladiator/philosopher/factory/RecommendFactory.java
- src/test/java/gladiator/philosopher/factory/ReportFactory.java
- src/test/java/gladiator/philosopher/factory/ThreadFactory.java
- src/test/java/gladiator/philosopher/mention/MentionServiceTest.java
- src/test/java/gladiator/philosopher/mention/MentionTest.java
> Category 테스트 및 테스트 가이드라인 작성

- .gitignore
- build.gradle
- settings.gradle
feat: gradle 파일 포함 및 gitignore 업데이트
> feat: gradle 파일 포함 및 gitignore 업데이트

- .github/workflows/gradle.yml
feat: Github Actions 적용 gradle 파일 추가
> feat: Github Actions 적용 gradle 파일 추가

- src/main/java/gladiator/philosopher/notification/controller/NotificationController.java
- src/main/java/gladiator/philosopher/notification/dto/NotificationResponseDto.java
- src/main/java/gladiator/philosopher/notification/service/NotificationServiceImpl.java
> refactor: Response Status 추가 및 불필요 코드 제거(#166)

- src/main/java/gladiator/philosopher/category/controller/CategoryController.java
- src/main/java/gladiator/philosopher/category/service/CategoryServiceImpl.java
> refactor: Category Status 추가 및 readOnly속성 추가 (#162)

- src/main/java/gladiator/philosopher/report/controller/ReportController.java
> refactor: report ResponseStatus 추가 (#169)

- src/main/java/gladiator/philosopher/comment/entity/Comment.java
- src/main/java/gladiator/philosopher/comment/repository/MentionRepository.java
- src/main/java/gladiator/philosopher/comment/service/CommentServiceImpl.java
- src/main/java/gladiator/philosopher/comment/service/MentionServiceImpl.java
Comment 및 Mention SoftDelete 적용(#164)
> Comment 및 Mention SoftDelete 적용(#164)

- src/main/java/gladiator/philosopher/auth/service/AuthService.java
- src/main/java/gladiator/philosopher/comment/dto/CommentResponseDto.java
- src/main/java/gladiator/philosopher/comment/repository/CommentCustomRepositoryImpl.java
- src/main/java/gladiator/philosopher/comment/service/CommentServiceImpl.java
- src/main/java/gladiator/philosopher/comment/service/MentionServiceImpl.java
- src/main/java/gladiator/philosopher/notification/service/NotificationService.java
- src/main/java/gladiator/philosopher/notification/service/NotificationServiceImpl.java
- src/main/java/gladiator/philosopher/thread/dto/ThreadResponseDto.java
- src/main/java/gladiator/philosopher/thread/dto/ThreadSimpleResponseDto.java
- src/main/java/gladiator/philosopher/thread/repository/ThreadCustomRepositoryImpl.java
- src/test/java/gladiator/philosopher/notification/NotificationServiceTest.java
Comment 조회시 사용자 프로필 이미지 응답값에 포함
Thread 조회시 사용자 프로필 이미지 응답값에 포함
Comment Mention시 당사자에게 알림기능
구현했습니다.
close #195 #197 #198
> #195 #197 #198 관련 작업 진행 PR

- src/main/java/gladiator/philosopher/comment/entity/Comment.java
- src/main/java/gladiator/philosopher/comment/service/MentionServiceImpl.java
> fix: 삭제한 댓글이 멘션되는 버그 수정(#202)

- src/main/java/gladiator/philosopher/PhilosopherApplication.java
- src/main/java/gladiator/philosopher/common/config/RedisConfig.java
- src/main/java/gladiator/philosopher/common/util/RedisUtil.java
- src/main/java/gladiator/philosopher/scheduler/ScheduleTasks.java
- src/main/java/gladiator/philosopher/thread/controller/ThreadController.java
- src/main/java/gladiator/philosopher/thread/service/ThreadService.java
- src/main/java/gladiator/philosopher/thread/service/ThreadServiceImpl.java
- src/test/java/gladiator/philosopher/thread/service/ThreadServiceImplTest.java
Post => Thread 스케쥴러 적용 및 종료 시간 하루 뒤 자정으로 변경 - redis에 필요한 정보 넣기
> Post => Thread 스케쥴러 적용 및 종료 시간 하루 뒤 자정으로 변경 - redis에 필요한 정보 넣기

- src/main/java/gladiator/philosopher/thread/controller/ThreadController.java
- src/main/java/gladiator/philosopher/thread/dto/ThreadResponseDto.java
- src/main/java/gladiator/philosopher/thread/entity/Thread.java
- src/main/java/gladiator/philosopher/thread/entity/ThreadOpinion.java
- src/main/java/gladiator/philosopher/thread/repository/ThreadCustomRepositoryImpl.java
- src/main/java/gladiator/philosopher/thread/service/ThreadService.java
- src/main/java/gladiator/philosopher/thread/service/ThreadServiceImpl.java
refactor: Thread ERD Update 및 API 최신화 + 가독성 추가(총정리)(#240)
close #240
> refactor: Thread ERD Update 및 API 최신화 + 가독성 추가(총정리)(#240)

- src/main/java/gladiator/philosopher/notification/controller/NotificationController.java
- src/main/java/gladiator/philosopher/notification/dto/NotificationResponseDto.java
- src/main/java/gladiator/philosopher/notification/repository/EmitterRepository.java
- src/main/java/gladiator/philosopher/notification/repository/EmitterRepositoryImpl.java
- src/main/java/gladiator/philosopher/notification/service/NotificationService.java
- src/main/java/gladiator/philosopher/notification/service/NotificationServiceImpl.java
- src/main/java/gladiator/philosopher/recommend/controller/RecommendController.java
- src/main/java/gladiator/philosopher/recommend/service/RecommendServiceImpl.java
refactor: Recommend ERD Update 및 API 최신화 + 가독성 추가(총정리)(#243)
close #243
> refactor: Recommend ERD Update 및 API 최신화 + 가독성 추가(총정리)(#243)

- src/main/java/gladiator/philosopher/report/controller/ReportController.java
- src/main/java/gladiator/philosopher/report/service/ReportServiceImpl.java
refactor: Report ERD Update 및 API 최신화 + 가독성 추가(총정리)(#242)
close #242
> refactor: Report ERD Update 및 API 최신화 + 가독성 추가(총정리)(#242)

- src/main/java/gladiator/philosopher/comment/entity/Comment.java
- src/main/java/gladiator/philosopher/post/entity/Post.java
- src/main/java/gladiator/philosopher/report/entity/Report.java
- src/main/java/gladiator/philosopher/thread/entity/Thread.java
> fix: content 타입 lob 적용
